#!/bin/sh

APPDIR=$(dirname "$0")
java  -Djava.library.path="$APPDIR:$APPDIR\lib" -cp "$APPDIR/lib/instapop_3D.jar:$APPDIR/lib/core.jar:$APPDIR/lib/gluegen-rt.jar:$APPDIR/lib/jogl.all.jar:$APPDIR/lib/nativewindow.all.jar:$APPDIR/lib/opengl.jar:$APPDIR/lib/commons-codec-1.4.jar:$APPDIR/lib/commons-logging-1.1.1.jar:$APPDIR/lib/http.jar:$APPDIR/lib/httpclient-4.1.2.jar:$APPDIR/lib/httpclient-cache-4.1.2.jar:$APPDIR/lib/httpcore-4.1.2.jar:$APPDIR/lib/httpmime-4.1.2.jar:$APPDIR/lib/signpost-commonshttp4-1.2.1.1.jar:$APPDIR/lib/signpost-core-1.2.1.1.jar:$APPDIR/lib/stringtree-json-2.0.10.jar:$APPDIR/lib/jl1.0.jar:$APPDIR/lib/jsminim.jar:$APPDIR/lib/minim-spi.jar:$APPDIR/lib/minim.jar:$APPDIR/lib/mp3spi1.9.4.jar:$APPDIR/lib/tritonus_aos.jar:$APPDIR/lib/tritonus_share.jar" instapop_3D
